---
version: 1.4
prefs:
  runLog:
    type: file
    path: /home/dani/.jobber.log
    maxFileLen: 100m
    maxHistories: 1
jobs:
  tldr:
    time: '0 0 0 * * *'
    cmd: tldr --update

  bugwarrior:
    time: '0 0 0 * * *'
    cmd: zsh -i -c bugwarrior-pull

  backup_taskwarrior:
    time: '0 */5 * * * *'
    cmd: 'cp -r ~/.task/* ~/Nextcloud/taskwarrior'
