# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install AUR packages
      aur:
        name: '{{ item }}'
        skip_installed: true
      loop:
        - shellcheck
        - lab
        - jq
        - yq
        - ffsend-bin
        - krew-bin
        - neovim
        - alacritty-git
        - broot
        - lsd
        - oh-my-zsh-git
        - flameshot-git
        - git-standup-git
        - xautolock
        - xorg-xinit
        - python-virtualenv
        - rofi
        - xorg
        - dnsutils
        - dunst
        - diskus
        - feh
        - os-prober
        - tmux
        - networkmanager
        - network-manager-applet
        - enpass-bin
        - i3-gaps
        - i3status
        - i3blocks
        - i3lock
        - xf86-video-intel
        - task
        - bandwhich
        - yamllint
        - docker
        - docker-compose
        - shellshock
        - terraform
        - ruby
        - aws-cli
        - google-cloud-sdk
        - hub
        - fd
        - procs
        - nodejs
        - etcher
        - imagemagick
        - tldr
        - httpie
        - dropbox
        - openssh
        - ripgrep
        - rsync
        - spotify
        - gnome-alsamixer
        - slack-desktop
        - mimeo
        - unzip
