# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install AUR packages
      aur:
        name: '{{ item }}'
        skip_installed: true
      loop:
        - shellcheck
        - lab
        - jq
        - yq
        - ffsend-bin
