# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    # task-runner
    # - shell: curl -sL https://taskfile.dev/install.sh |\
    # sh && mv ./bin/task /usr/local/bin/task-runner
    #
    # add docker group
    - name: add me to docker group
      become: true
      user:
        name: adin
        groups: docker
        append: true
      tags: docker

    # lightdm
    # - aur: name=lightdm skip_installed=true

    # lightdm
    # $ deps- aur: name=lightdm-webkit-greeter skip_installed=true

    # lightdm-litarvan
    # -$deps aur: name=lightdm-webkite-theme-litarvan skip_installed=true

    # terraform
    - aur: name=terraform skip_installed=true

    # ruby
    - aur: name=ruby skip_installed=true

    # aws-cli
    - aur: name=aws-cli skip_installed=true

    # gcloud
    - aur: name=google-cloud-sdk skip_installed=true

    # hub-git
    - aur: name=hub skip_installed=true

    # fd
    - aur: name=fd skip_installed=true

    # procs
    - aur: name=procs skip_installed=true

    # vim-eunuch
    - aur: name=vim-eunuch skip_installed=true

    # mimeo
    - aur: name=mimeo skip_installed=true

    # setup mimeo
    - name: setup firefox as default app
      shell: mimeo --prefer firefox

    # Add gocode golang package
    - name: Go Gocode
      shell: go get -u github.com/stamblerre/gocode

    # procs
    - aur: name=procs skip_installed=true

    # setup nvim as git editor
    - name: setup git editor
      shell: git config --global core.editor "nvim"

    # nodejs
    - aur: name=nodejs skip_installed=true

    # Neovim gem
    - gem:
        name: neovim

    # Json gem
    - gem:
        name: json

    # etcher
    - aur: name=etcher skip_installed=true

    # scrot screenshot
    - aur: name=scrot skip_installed=true

    # imagemagick
    - aur: name=imagemagick skip_installed=true

    # tldr
    # - aur: name=tldr++ skip_installed=true

    # httpie
    - aur: name=httpie skip_installed=true

    # awless
    - aur: name=awless skip_installed=true

    # dropbox
    - aur: name=dropbox skip_installed=true

    # openssh
    - aur: name=openssh skip_installed=true

    # rg
    - aur: name=ripgrep skip_installed=true

    # rsync
    - aur: name=rsync skip_installed=true

    # unzip
    - aur: name=unzip skip_installed=true

    # snap
    - aur: name=snapd skip_installed=true

    # spotify
    - aur: name=spotify skip_installed=true

    # alsamixer utils
    - aur: name=gnome-alsamixer skip_installed=true

    # slack
    - aur: name=slack-desktop skip_installed=true

    # power manager
    - aur: name=xfce4-power-manager skip_installed=true

    # glibc
    - aur: name=glibc skip_installed=true

    # powerline fonts
    - aur: name=powerline-fonts-git skip_installed=true

    # kubectl
    - aur: name=kubectl-bin skip_installed=true

    # kubectx & kubens
    - aur: name=kubectx skip_installed=true

    # bat
    - aur: name=bat skip_installed=true

    # material design icons
    - aur: name=ttf-material-design-icons-git skip_installed=true

    # ttf-ionicons
    - aur: name=ttf-ionicons skip_installed=true

    # simplescreenrecorder
    - aur: name=simplescreenrecorder skip_installed=true

    # unrar
    - aur: name=unrar skip_installed=true

    # tzupdate
    - aur: name=tzupdate skip_installed=true

    # vimplug
    - name: vim-plug
      # yamllint disable-line
      shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: nvim-setup
      shell: nvim +PlugInstall +qall +silent

    - name: fzf install
      shell: ~/.fzf/install

    # npm
    - name: Install npm
      aur:
        name: npm
        skip_installed: true

    - name: Install git-delta
      aur:
        name: git-delta
        skip_installed: true

    - name: Install eslint-airbnb
      shell: "npx install-peerdeps --global eslint-config-airbnb"
      # important stuff
    - say:
        msg: "chmod id_rsa now"
        voice: Zarvox
      delegate_to: localhost

    - say:
        msg: "run os-prober"
        voice: Zarvox
      delegate_to: localhost
