---
- hosts: 127.0.0.1
  connection: local
  #vars_prompt:
  #  - name: docker deps
  #    prompt: "Remove make dependecies after install? [y/N]"
  #    default: "y"

  tasks:
    #install neovim
    - aur: name=neovim skip_installed=true

    # install oh-my-zsh
    - aur: name=oh-my-zsh-git skip_installed=true

    #install xorg-xinit/start
    - aur: name=xorg-xinit skip_installed=true

    #install rofi
    - aur: name=rofi skip_installed=true

    #install xorg
    - aur: name=xorg skip_installed=true

    #install tmux
    - aur: name=tmux skip_installed=true

    #install networkmanager
    - aur: name=networkmanager skip_installed=true

    #install np-applet
    - aur: name=network-manager-applet skip_installed=true

    #install enpass-bin
    - aur: name=enpass-bin skip_installed=true

    #install chromium
    - aur: name=chromium skip_installed=true

    #install i3-gaps
    - aur: name=i3-gaps skip_installed=true

    #install i3-gaps
    - aur: name=i3status skip_installed=true

    #install i3-gaps
    - aur: name=i3blocks skip_installed=true

    #install i3-gaps
    - aur: name=i3lock skip_installed=true

    # graphics
    - aur: name=xf86-video-intel skip_installed=true

    # taskwarrior
    - aur: name=task skip_installed=true

    # yamllint
    - aur: name=yamllint skip_installed=true

    # docker
    # - aur: name=docker-git skip_installed=true

    # docker-compose
    - aur: name=docker-compose skip_installed=true

    - name: add me to docker group
      become: true
      user:
        name: adin
        groups: docker
        append: true
      tags: docker

    # lightdm
    #- aur: name=lightdm skip_installed=true

    # lightdm
    #$ deps- aur: name=lightdm-webkit-greeter skip_installed=true

    # lightdm-litarvan
    #-$deps aur: name=lightdm-webkite-theme-litarvan skip_installed=true

    # terraform
    - aur: name=terraform skip_installed=true

    # aws-cli
    - aur: name=aws-cli skip_installed=true

    # gcloud
    - aur: name=google-cloud-sdk skip_installed=true

    # hub-git
    - aur: name=hub-git skip_installed=true

    # nvim-ycm
    - aur: name=neovim-youcompleteme-core-git skip_installed=true

    # fd
    - aur: name=fd skip_installed=true

    # diff-so-fany
    - aur: name=diff-so-fancy skip_installed=true

    # setup d-f-s
    - name: setup dfs
      shell: git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

    # setup nvim as git editor
    - name: setup git editor
      shell: git config --global core.editor "nvim"

    # nodejs
    - aur: name=nodejs skip_installed=true

    # alacritty
    - aur: name=alacritty-git skip_installed=true

    # httpie
    - aur: name=httpie skip_installed=true

    # awless
    - aur: name=awless skip_installed=true

    # dropbox
    - aur: name=dropbox skip_installed=true

    # openssh
    - aur: name=openssh skip_installed=true

    # rg
    - aur: name=ripgrep skip_installed=true

    # rg
    - aur: name=slack-desktop skip_installed=true

    # rg
    - aur: name=whatsapp-desktop skip_installed=true

    # pwr manager
    - aur: name=xfce4-power-manager skip_installed=true

    # rg
    - aur: name=glibc skip_installed=true

    # rg
    - aur: name=powerline-fonts-git skip_installed=true

    - name: vim-plug
      shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: nvim-setup
      shell: nvim +PlugInstall +qall +silent

    - name: fzf install
      shell: ~/.fzf/install

    - say:
        msg: "chmod id_rsa now"
        voice: Zarvox
      delegate_to: localhost
