# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local
  # vars_prompt:
  #  - name: docker deps
  #    prompt: "Remove make dependecies after install? [y/N]"
  #    default: "y"

  tasks:
    # install neovim
    - aur: name=neovim skip_installed=true

    # install oh-my-zsh
    - aur: name=oh-my-zsh-git skip_installed=true

    # install autolock
    - aur: name=xautolock skip_installed=true

    # install xorg-xinit/start
    - aur: name=xorg-xinit skip_installed=true

    # install rofi
    - aur: name=rofi skip_installed=true

    # install xorg
    - aur: name=xorg skip_installed=true

    # install dns-utils
    - aur: name=dnsutils skip_installed=true

    # install dunst
    - aur: name=dunst skip_installed=true

    # install feh
    - aur: name=feh skip_installed=true

    # install osprober
    - aur: name=os-prober skip_installed=true

    # install tmux
    - aur: name=tmux skip_installed=true

    # install networkmanager
    - aur: name=networkmanager skip_installed=true

    # install np-applet
    - aur: name=network-manager-applet skip_installed=true

    # install enpass-bin
    - aur: name=enpass-bin skip_installed=true

    # install chromium
    - aur: name=chromium skip_installed=true

    # install i3-gaps
    - aur: name=i3-gaps skip_installed=true

    # install i3-gaps
    - aur: name=i3status skip_installed=true

    # install i3-gaps
    - aur: name=i3blocks skip_installed=true

    # install i3-gaps
    - aur: name=i3lock skip_installed=true

    # graphics
    - aur: name=xf86-video-intel skip_installed=true

    # taskwarrior
    - aur: name=task skip_installed=true

    # yamllint
    - aur: name=yamllint skip_installed=true

    # docker
    # - aur: name=docker-git skip_installed=true

    # docker-compose
    - aur: name=docker-compose skip_installed=true

# add docker group
    - name: add me to docker group
      become: true
      user:
        name: adin
        groups: docker
        append: true
      tags: docker

    # lightdm
    # - aur: name=lightdm skip_installed=true

    # lightdm
    # $ deps- aur: name=lightdm-webkit-greeter skip_installed=true

    # lightdm-litarvan
    # -$deps aur: name=lightdm-webkite-theme-litarvan skip_installed=true

    # terraform
    - aur: name=terraform skip_installed=true

    # aws-cli
    - aur: name=aws-cli skip_installed=true

    # gcloud
    - aur: name=google-cloud-sdk skip_installed=true

    # hub-git
    - aur: name=hub-git skip_installed=true

    # nvim-ycm
    - aur: name=neovim-youcompleteme-core-git skip_installed=true

    # fd
    - aur: name=fd skip_installed=true

    # diff-so-fany
    - aur: name=diff-so-fancy skip_installed=true

    # setup d-f-s
    - name: setup dfs
      shell: git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

    # setup nvim as git editor
    - name: setup git editor
      shell: git config --global core.editor "nvim"

    # nodejs
    - aur: name=nodejs skip_installed=true

    # yarn
    - name: Install yarn
      npm:
        name: yarn
        global: true

    # scrot screenshot
    - aur: name=scrot skip_installed=true

    # imagemagick
    - aur: name=imagemagick skip_installed=true

    # tldr
    - aur: name=tldr-nodejs skip_installed=true

    # alacritty
    - aur: name=alacritty-git skip_installed=true

    # httpie
    - aur: name=httpie skip_installed=true

    # awless
    - aur: name=awless skip_installed=true

    # dropbox
    - aur: name=dropbox skip_installed=true

    # openssh
    - aur: name=openssh skip_installed=true

    # rg
    - aur: name=ripgrep skip_installed=true

    # rsync
    - aur: name=rsync skip_installed=true

    # unzip
    - aur: name=unzip skip_installed=true

    # snap
    - aur: name=snapd skip_installed=true

    # spotify
    - aur: name=spotify skip_installed=true

    # alsamixer utils
    - aur: name=alsamixer-utils skip_installed=true

    # slack
    - aur: name=slack-desktop skip_installed=true

    # whatsapp
    - aur: name=whatsapp-desktop skip_installed=true

    # power manager
    - aur: name=xfce4-power-manager skip_installed=true

    # glibc
    - aur: name=glibc skip_installed=true

    # powerline fonts
    - aur: name=powerline-fonts-git skip_installed=true

    # bat
    - aur: name=bat skip_installed=true

    # material design icons
    - aur: name=ttf-material-design-icons-git skip_installed=true

    # ttf-ionicons
    - aur: name=ttf-ionicons skip_installed=true

    # simplescreenrecorder
    - aur: name=simplescreenrecorder skip_installed=true

    # unrar
    - aur: name=unrar skip_installed=true

    - name: fonts
      # yamllint disable
      shell: >
        git clone --depth 1 https://github.com/stephenhutchings/typicons.font
        ln -s ./fonts/typicons.font/src/font/typicons.ttf /usr/share/fonts/TTF
        git clone --depth 1 https://github.com/FortAwesome/Font-Awesome
        ln -s "$PWD/Font-Awesome/otfs/Font Awesome 5 Free-Solid-900.otf" /usr/share/fonts/OTF/
        ln -s "$PWD/Font-Awesome/otfs/Font Awesome 5 Free-Regular-400.otf" /usr/share/fonts/OTF/
        ln -s "$PWD/Font-Awesome/otfs/Font Awesome 5 Brands-Regular-400.otf" /usr/share/fonts/OTF/
        git clone --depth 1 https://github.com/google/material-design-icons
        ln -s $PWD/material-design-icons/iconfont/MaterialIcons-Regular.ttf /usr/share/fonts/TTF

        git clone --depth 1 https://github.com/Templarian/MaterialDesign-Webfont
        ln -s $PWD/MaterialDesign-Webfont/fonts/materialdesignicons-webfont.ttf /usr/share/fonts/TTF/
        git clone --depth 1 https://github.com/ionic-team/ionicons
        ln -s $PWD/ionicons/docs/fonts/ionicons.ttf /usr/share/fonts/TTF
      # yamllint enable


    # vimplug
    - name: vim-plug
      # yamllint disable-line
      shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: nvim-setup
      shell: nvim +PlugInstall +qall +silent

    - name: fzf install
      shell: ~/.fzf/install


      # important stuff
    - say:
        msg: "chmod id_rsa now"
        voice: Zarvox
      delegate_to: localhost

    - say:
        msg: "run os-prober"
        voice: Zarvox
      delegate_to: localhost
