# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    # task-runner
    # - shell: curl -sL https://taskfile.dev/install.sh |\
    # sh && mv ./bin/task /usr/local/bin/task-runner

    # lightdm
    # - aur: name=lightdm skip_installed=true

    # lightdm
    # $ deps- aur: name=lightdm-webkit-greeter skip_installed=true

    # lightdm-litarvan
    # -$deps aur: name=lightdm-webkite-theme-litarvan skip_installed=true
