# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    # install neovim
    - aur: name=neovim skip_installed=true

    # install lsd
    - aur: name=lsd skip_installed=true

    # install oh-my-zsh
    - aur: name=oh-my-zsh-git skip_installed=true

    # install flameshot-git
    - aur: name=flameshot-git skip_installed=true

    # install gi standup
    - aur: name=git-standup-git skip_installed=true

    # install autolock
    - aur: name=xautolock skip_installed=true

    # install xorg-xinit/start
    - aur: name=xorg-xinit skip_installed=true

    # python venv
    - aur: name=python-virtualenv skip_installed=true

    # install rofi
    - aur: name=rofi skip_installed=true

    # install xorg
    - aur: name=xorg skip_installed=true

    # install dns-utils
    - aur: name=dnsutils skip_installed=true

    # install dunst
    - aur: name=dunst skip_installed=true

    # install diskus (du -sh)
    - aur: name=diskus skip_installed=true

    # install feh
    - aur: name=feh skip_installed=true

    # install osprober
    - aur: name=os-prober skip_installed=true

    # install tmux
    - aur: name=tmux skip_installed=true

    # install networkmanager
    - aur: name=networkmanager skip_installed=true

    # install np-applet
    - aur: name=network-manager-applet skip_installed=true

    # install enpass-bin
    - aur: name=enpass-bin skip_installed=true

    # install chromium
    - aur: name=chromium skip_installed=true

    # install i3-gaps
    - aur: name=i3-gaps skip_installed=true

    # install i3-gaps
    - aur: name=i3status skip_installed=true

    # install i3-gaps
    - aur: name=i3blocks skip_installed=true

    # install i3-gaps
    - aur: name=i3lock skip_installed=true

    # graphics
    - aur: name=xf86-video-intel skip_installed=true

    # taskwarrior
    - aur: name=task skip_installed=true

    # task-runner
    - shell: curl -sL https://taskfile.dev/install.sh |\
        sh && mv ./bin/task /usr/local/bin/task-runner

    # py-poetry
    - shell: curl -sSL \
        https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py |\
        python

    # yamllint
    - aur: name=yamllint skip_installed=true

    # docker
    # - aur: name=docker-git skip_installed=true

    # docker-compose
    - aur: name=docker-compose skip_installed=true

    # shellshock without haskell dep
    - aur: name=shellshock-static skip_installed=true

    # downgrade
    - aur: name=shellshock-static skip_installed=true

    # pipreqs
    - pip:
        name: pipreqs

    # Add PyGithub (ansible githooks)
    - pip:
        name: PyGithub

    # Pyhelm
    - pip:
        name: PyHelm

    # Pyls
    - pip:
        name: python-language-server[all]

    # Pyls-isort
    - pip:
        name: pyls-isort

    # Pyls-mypy
    - pip:
        name: pyls-mypy

    # Pyls-black
    - pip:
        name: pyls-black

    # Django-stubs
    - pip:
        name: django-stubs

    # Add postgres
    - pip:
        name: psycopg2

    # Add vimvint
    - pip:
        name: vimvint

    # Add rebound-cli
    - pip:
        name: rebound-cli

    # Add mypy
    - pip:
        name: mypy

    # Add PynVim
    - pip:
        name: pynvim

    # Add Jedi for deoplete
    - pip:
        name: jedi

    # add docker group
    - name: add me to docker group
      become: true
      user:
        name: adin
        groups: docker
        append: true
      tags: docker

    # lightdm
    # - aur: name=lightdm skip_installed=true

    # lightdm
    # $ deps- aur: name=lightdm-webkit-greeter skip_installed=true

    # lightdm-litarvan
    # -$deps aur: name=lightdm-webkite-theme-litarvan skip_installed=true

    # terraform
    - aur: name=terraform skip_installed=true

    # ruby
    - aur: name=ruby skip_installed=true

    # aws-cli
    - aur: name=aws-cli skip_installed=true

    # gcloud
    - aur: name=google-cloud-sdk skip_installed=true

    # hub-git
    - aur: name=hub-git skip_installed=true

    # fd
    - aur: name=fd skip_installed=true

    # procs
    - aur: name=procs skip_installed=true

    # vim-eunuch
    - aur: name=vim-eunuch skip_installed=true

    # mimeo
    - aur: name=mimeo skip_installed=true

    # setup mimeo
    - name: setup firefox as default app
      shell: mimeo --prefer firefox

    # Add gocode golang package
    - name: Go Gocode
      shell: go get -u github.com/stamblerre/gocode

    # Add efm-langserver
    - name: Go Get efm lang server
      shell: go get -u github.com/mattn/efm-langserver/cmd/efm-langserver

    - name: Setup diff-so-fancy for git
      shell: git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

    # diff-so-fany
    - aur: name=diff-so-fancy skip_installed=true

    # procs
    - aur: name=procs skip_installed=true

    # setup d-f-s
    - name: setup dfs
      shell: git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

    # setup nvim as git editor
    - name: setup git editor
      shell: git config --global core.editor "nvim"

    # nodejs
    - aur: name=nodejs skip_installed=true

    # yarn
    - name: Install yarn
      npm:
        name: yarn
        global: true

    # yarn
    - name: Install yarn
      npm:
        name: write-good
        global: true

    # terser
    - name: Install terser
      npm:
        name: terser
        global: true

    # ternjs
    - name: Install tern
      npm:
        name: tern
        global: true
    # Vtop
    - name: Install vtop
      npm:
        name: vtop
        global: true

    - name: Install neovim
      npm:
        name: neovim
        global: true

    - name: Install tstags
      npm:
        name: tstags
        global: true

    - name: Install dockerfile-language-server-nodejs
      npm:
        name: dockerfile-language-server-nodejs
        global: true

    - name: Install npx
      npm:
        name: npx
        global: true

    - name: Install prettier
      npm:
        name: prettier
        global: true

    - name: Install eslint-prettier
      npm:
        name: prettier-eslint
        global: true

    - name: Install eslint-plugin-template
      npm:
        name: eslint-plugin-template
        global: true

    - name: Install markdownlint-cli
      npm:
        name: markdownlint-cli
        global: true

    - name: Install htmlhint
      npm:
        name: htmlhint
        global: true

    - name: Install eslint-html
      npm:
        name: eslint-plugin-html
        global: true

    - name: Install eslint-prettier
      npm:
        name: eslint-plugin-prettier
        global: true

    - name: Install stylelint
      npm:
        name: stylelint
        global: true

    - name: Install stylelint-config-airbnb
      npm:
        name: stylelint-config-airbnb
        global: true

    - name: Install stylelint-order
      npm:
        name: stylelint-order
        global: true

    - name: Install stylelint-scss
      npm:
        name: stylelint-order
        global: true

    - name: Install eslint-airbnb
      shell: "npx install-peerdeps --global eslint-config-airbnb"

    - name: Install tstags
      shell: "npm install --global git+https://github.com/Perlence/tstags.git"

    - name: Install tstags
      shell: "npm install --global git+https://github.com/ramitos/jsctags.git"

    # Neovim gem
    - gem:
        name: neovim

    # Json gem
    - gem:
        name: json

    # etcher
    - aur: name=etcher skip_installed=true

    # scrot screenshot
    - aur: name=scrot skip_installed=true

    # imagemagick
    - aur: name=imagemagick skip_installed=true

    # tldr
    - aur: name=tldr-nodejs skip_installed=true

    # alacritty
    - aur: name=alacritty-git skip_installed=true

    # httpie
    - aur: name=httpie skip_installed=true

    # awless
    - aur: name=awless skip_installed=true

    # dropbox
    - aur: name=dropbox skip_installed=true

    # openssh
    - aur: name=openssh skip_installed=true

    # rg
    - aur: name=ripgrep skip_installed=true

    # rsync
    - aur: name=rsync skip_installed=true

    # unzip
    - aur: name=unzip skip_installed=true

    # snap
    - aur: name=snapd skip_installed=true

    # spotify
    - aur: name=spotify skip_installed=true

    # alsamixer utils
    - aur: name=alsamixer-utils skip_installed=true

    # slack
    - aur: name=slack-desktop skip_installed=true

    # whatsapp
    - aur: name=whatsapp-desktop skip_installed=true

    # power manager
    - aur: name=xfce4-power-manager skip_installed=true

    # glibc
    - aur: name=glibc skip_installed=true

    # powerline fonts
    - aur: name=powerline-fonts-git skip_installed=true

    # kubectl
    - aur: name=kubectl-bin skip_installed=true

    # kubectx & kubens
    - aur: name=kubectx skip_installed=true

    # bat
    - aur: name=bat skip_installed=true

    # material design icons
    - aur: name=ttf-material-design-icons-git skip_installed=true

    # ttf-ionicons
    - aur: name=ttf-ionicons skip_installed=true

    # simplescreenrecorder
    - aur: name=simplescreenrecorder skip_installed=true

    # unrar
    - aur: name=unrar skip_installed=true

    # tzupdate
    - aur: name=tzupdate skip_installed=true

    - name: fonts
      # yamllint disable
      shell: >
        git clone --depth 1 https://github.com/stephenhutchings/typicons.font
        ln -s ./fonts/typicons.font/src/font/typicons.ttf /usr/share/fonts/TTF
        git clone --depth 1 https://github.com/FortAwesome/Font-Awesome
        ln -s "$PWD/Font-Awesome/otfs/Font Awesome 5 Free-Solid-900.otf" /usr/share/fonts/OTF/
        ln -s "$PWD/Font-Awesome/otfs/Font Awesome 5 Free-Regular-400.otf" /usr/share/fonts/OTF/
        ln -s "$PWD/Font-Awesome/otfs/Font Awesome 5 Brands-Regular-400.otf" /usr/share/fonts/OTF/
        git clone --depth 1 https://github.com/google/material-design-icons
        ln -s $PWD/material-design-icons/iconfont/MaterialIcons-Regular.ttf /usr/share/fonts/TTF

        git clone --depth 1 https://github.com/Templarian/MaterialDesign-Webfont
        ln -s $PWD/MaterialDesign-Webfont/fonts/materialdesignicons-webfont.ttf /usr/share/fonts/TTF/
        git clone --depth 1 https://github.com/ionic-team/ionicons
        ln -s $PWD/ionicons/docs/fonts/ionicons.ttf /usr/share/fonts/TTF
      # yamllint enable


    # vimplug
    - name: vim-plug
      # yamllint disable-line
      shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: nvim-setup
      shell: nvim +PlugInstall +qall +silent

    - name: fzf install
      shell: ~/.fzf/install

      # important stuff
    - say:
        msg: "chmod id_rsa now"
        voice: Zarvox
      delegate_to: localhost

    - say:
        msg: "run os-prober"
        voice: Zarvox
      delegate_to: localhost
