---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    user: adin
  tasks:

    - name: Directories
      file:
        path: '/home/{{ user }}/{{ item }}'
        state: directory
        owner: adin
        loop:
          - tempinstall
          - .ssh
          - .i3
          - .config
