# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install NPM packages
      npm:
        name: '{{ item }}'
        global: true
      loop:
        - js-beautify
        - instant-markdown-d
