# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install PIP packages
      pip:
        name: '{{ item }}'
      loop:
        - ansible-lint
        - cookiecutter
        - poetry
        - pipreqs
        - pypyp
        - PyGithub
        - grpcio
        - openshift
        - PyHelm
        - python-language-server[all]
        - pyls-isort
        - pyls-mypy
        - pyls-black
        - django-stubs
        - psycopg2
        - vim-vint
        - rebound-cli
        - mypy
        - pynvim
        - jedi
        - requests
        - docker-compose
        - dbus-python
        - awscli
