---
- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
      # background image
    - copy:
        src: /home/adin/.dotfiles/images/mostar.jpg
        dest: /usr/share/lightdm-webkit/themes/litarvan/images/background.png

