
yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install NPM packages
      npm:
        name: '{{ item }}'
        global: true
      loop:
        - instant-markdown-d
        - yarn
        - jsonlint
        - write-good
        - tldr
        - terser
        - tern
        - neovim
        - dockerfile-language-server-nodejs
        - prettier
        - markdownlint-cli
        - htmlhint
        - stylelint
        - stylelint-config-recommended
        - stylelint-order
        - stylelint-scss
